using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerBehaviour : MonoBehaviour
{
    public float horizontalForce;
    public float verticalForce;
    public bool isGrounded;

    private Rigidbody2D rigidBody2D;
    
    // Start is called before the first frame update
    void Start()
    {
        rigidBody2D = GetComponent<Rigidbody2D>();
    }

    // Update is called once per frame
    void Update()
    {
        float x = 0.0f;
        float y = 0.0f;

        if (isGrounded)
        {
            x = Input.GetAxisRaw("Horizontal");
            y = Input.GetAxisRaw("Jump");

            // check if player is moving
            if (x != 0)
            {
                transform.localScale = new Vector3(Mathf.RoundToInt(x), 1.0f);
            }
            
        }

        Vector2 movementVector = new Vector2(x * horizontalForce, y * verticalForce);
        rigidBody2D.AddForce(movementVector);
    }

    void OnCollisionEnter2D(Collision2D other)
    {
        if (other.gameObject.CompareTag("Platform"))
        {
            isGrounded = true;
        }
    }

    void OnCollisionExit2D(Collision2D other)
    {
        if (other.gameObject.CompareTag("Platform"))
        {
            isGrounded = false;
        }
    }

}
